### ISSUE TITLE
Chapter references in book differ from repository

### ISSUE THREAD

**Issue by scottfurry** [PacktPublishing/CMake-Best-Practices#45]
Got my hands on a sample of first chapter. In going through code given, there are noticeable differences in how book refers to chapter code in git repository and existing git repository.

For example, on page 7 is the section _Building your first project_, which walks user through the basic of CMake usage. The book sample I saw showed chapter code as `chapter_1`. However, repository uses `chapter01`.

Also of note is that there are two references to chapter 13 code in repository (both `chapter_13` and `chapter13`). Unknown which reference is used in book.

Lack of consistency detracts from reading.

**Comment by bernedom** [comment]
Hi @scottfurry thank you very much for the feedback, I will take that up with the editors of the book and see if how we can correct that.

**Comment by bernedom** [comment]
This issue was adressed in the [second edition of CMake Best Practices](https://github.com/PacktPublishing/CMake-Best-Practices---2nd-Edition/)
