### ISSUE TITLE
might be good content but very bad explanation

### ISSUE THREAD

**Issue by gouldberg** [PacktPublishing/CMake-Best-Practices#46]
No basic minimum command explanation is clearly given. 
 cmake -S . -B ./build
 cmake -build ./build
 cmake -install ./build -prefix /tmp/install-test
Those commands firstly appears far at p.107  (so far from the 1st page).

Also install commands are described., but not 'uninstall' commands.
How to uninstall when after following this tutorial example ?
Many library is installed and stay ?  Nothing explanation.  With great care, I can not install without knowing installing effect and uninstalling commands.

**Comment by mustafakemalgilor** [comment]
Hello @gouldberg 

Unfortunately, CMake does not provide "uninstall" for install() at this moment. You can workaround this by providing your own uninstall steps by using "add_custom_target()", as can be seen in the following example: https://gitlab.kitware.com/cmake/community/-/wikis/FAQ#can-i-do-make-uninstall-with-cmake
